import { Company, Purchase, MedicalShop, Sale, MonthlyData, Transaction } from './types';

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'PharmaCorp International',
    contactPerson: 'John Smith',
    phone: '+1-555-0123',
    email: 'john.smith@pharmacorp.com',
    address: '123 Medical Plaza, Boston, MA',
    totalPurchases: 145000,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'MediLife Suppliers',
    contactPerson: 'Sarah Johnson',
    phone: '+1-555-0456',
    email: 'sarah.j@medilife.com',
    address: '456 Healthcare Blvd, New York, NY',
    totalPurchases: 98500,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Global Health Solutions',
    contactPerson: 'Michael Chen',
    phone: '+1-555-0789',
    email: 'mchen@globalhealthsol.com',
    address: '789 Wellness Ave, Chicago, IL',
    totalPurchases: 127000,
    createdAt: '2024-01-10',
  },
  {
    id: '4',
    name: 'BioMed Distributors',
    contactPerson: 'Emily Davis',
    phone: '+1-555-0321',
    email: 'emily.davis@biomed.com',
    address: '321 Pharma Street, Los Angeles, CA',
    totalPurchases: 82000,
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    name: 'Wellness Pharmaceuticals',
    contactPerson: 'Robert Wilson',
    phone: '+1-555-0654',
    email: 'r.wilson@wellnessph.com',
    address: '654 Medical Center, Houston, TX',
    totalPurchases: 113500,
    createdAt: '2024-02-12',
  },
];

export const mockPurchases: Purchase[] = [
  {
    id: 'p1',
    companyId: '1',
    companyName: 'PharmaCorp International',
    quantity: 5000,
    pricePerUnit: 12.5,
    totalCost: 62500,
    purchaseDate: '2024-03-15',
    receiptUrl: '/receipts/receipt-1.pdf',
    notes: 'Bulk order - pain relief medications',
  },
  {
    id: 'p2',
    companyId: '2',
    companyName: 'MediLife Suppliers',
    quantity: 3500,
    pricePerUnit: 15.0,
    totalCost: 52500,
    purchaseDate: '2024-03-18',
    receiptUrl: '/receipts/receipt-2.pdf',
    notes: 'Antibiotics and antivirals',
  },
  {
    id: 'p3',
    companyId: '3',
    companyName: 'Global Health Solutions',
    quantity: 4200,
    pricePerUnit: 18.5,
    totalCost: 77700,
    purchaseDate: '2024-03-20',
    receiptUrl: '/receipts/receipt-3.pdf',
  },
  {
    id: 'p4',
    companyId: '1',
    companyName: 'PharmaCorp International',
    quantity: 6000,
    pricePerUnit: 10.0,
    totalCost: 60000,
    purchaseDate: '2024-03-22',
    receiptUrl: '/receipts/receipt-4.pdf',
    notes: 'Vitamin supplements',
  },
  {
    id: 'p5',
    companyId: '4',
    companyName: 'BioMed Distributors',
    quantity: 2800,
    pricePerUnit: 22.0,
    totalCost: 61600,
    purchaseDate: '2024-03-25',
    receiptUrl: '/receipts/receipt-5.pdf',
  },
];

export const mockShops: MedicalShop[] = [
  {
    id: 's1',
    name: 'HealthCare Pharmacy',
    ownerName: 'Dr. Amanda Roberts',
    phone: '+1-555-1111',
    email: 'amanda@healthcare-pharmacy.com',
    address: '111 Main Street, Springfield',
    totalSales: 185000,
    createdAt: '2024-01-05',
  },
  {
    id: 's2',
    name: 'City Medical Store',
    ownerName: 'Mr. David Lee',
    phone: '+1-555-2222',
    email: 'david@citymedical.com',
    address: '222 Park Avenue, Riverside',
    totalSales: 156000,
    createdAt: '2024-01-12',
  },
  {
    id: 's3',
    name: 'Wellness Pharmacy Plus',
    ownerName: 'Mrs. Jennifer Brown',
    phone: '+1-555-3333',
    email: 'jennifer@wellnessplus.com',
    address: '333 Oak Street, Greenfield',
    totalSales: 142000,
    createdAt: '2024-02-01',
  },
  {
    id: 's4',
    name: 'Quick Care Pharmacy',
    ownerName: 'Dr. James Wilson',
    phone: '+1-555-4444',
    email: 'james@quickcare.com',
    address: '444 Elm Street, Lakeside',
    totalSales: 98000,
    createdAt: '2024-02-15',
  },
  {
    id: 's5',
    name: 'Family Health Pharmacy',
    ownerName: 'Mrs. Lisa Martinez',
    phone: '+1-555-5555',
    email: 'lisa@familyhealth.com',
    address: '555 Maple Drive, Hilltown',
    totalSales: 127000,
    createdAt: '2024-01-20',
  },
];

export const mockSales: Sale[] = [
  {
    id: 'sale1',
    shopId: 's1',
    shopName: 'HealthCare Pharmacy',
    quantity: 2500,
    pricePerUnit: 25.0,
    totalAmount: 62500,
    saleDate: '2024-03-16',
    profit: 31250,
    invoiceNumber: 'INV-2024-001',
  },
  {
    id: 'sale2',
    shopId: 's2',
    shopName: 'City Medical Store',
    quantity: 1800,
    pricePerUnit: 28.0,
    totalAmount: 50400,
    saleDate: '2024-03-19',
    profit: 23700,
    invoiceNumber: 'INV-2024-002',
  },
  {
    id: 'sale3',
    shopId: 's3',
    shopName: 'Wellness Pharmacy Plus',
    quantity: 2200,
    pricePerUnit: 32.0,
    totalAmount: 70400,
    saleDate: '2024-03-21',
    profit: 29700,
    invoiceNumber: 'INV-2024-003',
  },
  {
    id: 'sale4',
    shopId: 's1',
    shopName: 'HealthCare Pharmacy',
    quantity: 3000,
    pricePerUnit: 22.0,
    totalAmount: 66000,
    saleDate: '2024-03-23',
    profit: 36000,
    invoiceNumber: 'INV-2024-004',
  },
  {
    id: 'sale5',
    shopId: 's4',
    shopName: 'Quick Care Pharmacy',
    quantity: 1500,
    pricePerUnit: 35.0,
    totalAmount: 52500,
    saleDate: '2024-03-26',
    profit: 19500,
    invoiceNumber: 'INV-2024-005',
  },
];

export const mockMonthlyData: MonthlyData[] = [
  { month: 'Jan', purchases: 95000, sales: 125000, profit: 30000 },
  { month: 'Feb', purchases: 108000, sales: 142000, profit: 34000 },
  { month: 'Mar', purchases: 314300, sales: 301800, profit: 140150 },
  { month: 'Apr', purchases: 0, sales: 0, profit: 0 },
  { month: 'May', purchases: 0, sales: 0, profit: 0 },
  { month: 'Jun', purchases: 0, sales: 0, profit: 0 },
];

export const mockTransactions: Transaction[] = [
  ...mockPurchases.slice(0, 3).map(p => ({
    id: p.id,
    type: 'purchase' as const,
    party: p.companyName,
    amount: p.totalCost,
    date: p.purchaseDate,
    quantity: p.quantity,
  })),
  ...mockSales.slice(0, 3).map(s => ({
    id: s.id,
    type: 'sale' as const,
    party: s.shopName,
    amount: s.totalAmount,
    date: s.saleDate,
    quantity: s.quantity,
  })),
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
